<body>
    <div id="root"></div>
    <script src="https://unpkg.com/react@16.12.0/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@16.12.0/umd/react-dom.development.js"></script>
    <script src="https://unpkg.com/@babel/standalone@7.8.3/babel.js"></script>
    <script src="https://unpkg.com/prop-types@15.6.1/prop-types.js"></script>
    <script src="https://unpkg.com/react-error-boundary@1.2.5/dist/umd/react-error-boundary.js"></script>
    <script type="text/babel">
        const rootElement = document.getElementById('root')
        const ErrorBoundary = ReactErrorBoundary.ErrorBoundary;
        function ErrorFallback({error}){
            return (
                <div>
                    {/* controlling error by ErrorBoundary */}
                    <p> Something went wrong </p>
                    <pre>{error.message}</pre>
                </div>
            )
        }
        function Boom(){
            throw new Error("ðŸ’¥BoomðŸ’¥")
        }
        function App(){
            const [explode,setExplode] = React.useState(false)
            return (
                <div>
                    <div>
                        <button onClick = {() => setExplode(true)}>ðŸ’£</button>
                    </div>
                    <div>
                        <ErrorBoundary FallbackComponent={ErrorFallback}>
                        {explode? <Boom /> : "Push the button Max!"}
                        </ErrorBoundary>
                    </div>
                </div>
            )
        }

    
        ReactDOM.render(<App />, rootElement)
    </script>
</body>